on: [push]

name: CI build

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: oi-wiki-api
            asset_name: oi-wiki-api-linux-amd64
          - os: windows-latest
            artifact_name: oi-wiki-api.exe
            asset_name: oi-wiki-api-windows-amd64.exe
          - os: macos-latest
            artifact_name: oi-wiki-api
            asset_name: oi-wiki-api-macos-amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: Swatinem/rust-cache@v1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.artifact_name }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          
